#spring.application.name=IoTSystem
#
## ? ??i l?i t�n DB ? cu?i URL (hi?n t?i b?n ?ang ?? postgres ? nh?ng DB th?t c?a b?n l� "iot-system")
#spring.datasource.url=jdbc:postgresql://iotdbserver.postgres.database.azure.com:5432/iot-system?sslmode=require
#
## Username Azure PostgreSQL lu�n c� d?ng: <t�n_user>@<t�n_server>
#spring.datasource.username=postgreadmin
#
## ?? N?u password c� k� t? ??c bi?t (#, $, !, @, ?) th� b?t bu?c ?? trong d?u nh�y k�p
#spring.datasource.password=QUANGVINH3#
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Swagger
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#
## Hikari + SSL
#spring.datasource.hikari.data-source-properties.ssl=true
#spring.datasource.hikari.data-source-properties.sslmode=require



######################### TESTING ##############################

spring.application.name=IoTSystem

# K?t n?i MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/iot_rental
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate t? t?o ho?c c?p nh?t b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# VNPay Configuration
vnpay.version=2.1.0
vnpay.command=pay
vnpay.tmn-code=LSSYE5G8
vnpay.secret-key=5KN0SD3QXWE9K0I1JNW2G47F4OVJT1PR
vnpay.vnp-pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.vnp-return-url=http://localhost:8080/api/payment/vnpay-return
vnpay.vnp-api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
vnpay.order-type=other
vnpay.locale=vn
vnpay.currency-code=VND
vnpay.default-timeout=900
